### PR TITLE
Fix type exports

### LINKED ISSUE #2919: TS1203: Export assignment cannot be used when targeting  ECMAScript modules. Consider using 'export default' or another module format instead.
**Describe the bug**
Getting the following error:
```
tsc --noEmit        
../bla/node_modules/mathjs/types/index.d.ts:5:1 - error TS1203: Export assignment cannot be used when targeting 
ECMAScript modules. Consider using 'export default' or another module format instead.

5 export = math
  ~~~~~~~~~~~~~


Found 1 error in ../balances/node_modules/mathjs/types/index.d.ts:5
```

**To Reproduce**
I have `"type": "module"` in my `package.json` and 
```
"target": "ESNext",
"module": "ESNext",
"moduleResolution": "Node16"
```
in my TSConfig, using TS v5.0.2, it used to work with TS v4.9.5

### PR DESCRIPTION
**Pull request by josdejong**
Fixes #2919 by publishing two versions of the `types/index.d.ts` file with TypeScript type definitions.

See: https://github.com/josdejong/mathjs/issues/2919#issuecomment-1694338241

### CODE REVIEW

**Comment by josdejong** [comment]
This approach doesn't work unfortunately.

Closing in favor of #3079.
