### ISSUE TITLE
Code break on v3.14.0 and v3.14.1

### ISSUE THREAD

**Issue by berosoboy** [josdejong/mathjs#891]
I have the v13.3.0 installed via composer is working fine in the browser. But the following error occurred after upgrading to v3.14

```
Uncaught TypeError: i.clone is not a function
    at Object.n [as factory] (math.js:44126)
    at t (math.js:24569)
    at l (math.js:24935)
    at Object.get [as BigNumber] (math.js:1565)
    at n (math.js:24402)
    at math.js:24392
    at r.emit (math.js:58521)
    at Object.a [as config] (math.js:24664)
    at math.config.js:2
```

My math.config.js file:

```

math.config({
    number: 'BigNumber', // Default type of number: 'number' (default), 'BigNumber', or 'Fraction'
    precision: 64 // Number of significant digits for BigNumbers
});
```

**Comment by josdejong** [comment]
Thanks for reporting. 

How can I repeat your issue exactly? Do the examples that come with the library work normally or neither?

**Comment by berosoboy** [comment]
the problem occurs when I try to configure mathjs to use BigNumber

**Comment by josdejong** [comment]
Thanks, that helps. This is a bug in mathjs and not related to composer or something. Simply entering `math.config({number: 'BigNumber'})` in the browser you git this error. in node.js everything works fine.

**Comment by josdejong** [comment]
This should be fixed now in v3.14.2, see commit https://github.com/josdejong/mathjs/commit/b8b76cd5b752268269a5025a756706f77722a45e. For some reason the bundler picked the es6 version of the decimal.js library or something like that, and got back an object `{default: Decimal}` instead of `Decimal`.

**Comment by berosoboy** [comment]
It's working now. Thank you!
