### PR TITLE
operations between jagged arrays and scalars

### PR DESCRIPTION
**Pull request by dvd101x**
Hi, this is the proof of concept discussed at #3537

It's more inline with what Jos and Glen suggested as my initial idea was flawed. This PR only shows two main changes.

- refactors matAlgo14xDs to use it's DenseMatrix map method and includes a hack to make the matrix creation faster.
- makes a new matAlgo15xAs to map arrays that can be jagged or non homogeneous and there is no need to convert to matrix and then back to array.

My expectation is that all operations between Matrix|Array and scalar should be faster.

The new functionality is that it's possible to do stuff like

```js
math.add([1,[2,3]], 1)

math.config({matrix:"Array"})
math.evaluate("[1,[2,3]] + 1")
```

### CODE REVIEW

**Comment by josdejong** [comment]
Nice! This actually simplifies the code since you can "just" use the map function.

What are the next steps? Add some unit tests for jagged inputs, update docs, and see what the performance impact is?

**Comment by dvd101x** [comment]
Yes exactly, I will proceed with the next steps in the following weeks.

Maybe later I will come back to broadcasting jagged arrays.

File: src/type/matrix/utils/matAlgo14xDs.js [hunk 1]
```diff
@@ -34,42 +28,13 @@ export const createMatAlgo14xDs = /* #__PURE__ */ factory(name, dependencies, ({
     // process data types
     if (typeof adt === 'string') {
       // datatype
```
Comment (gwhitney) [inline src/type/matrix/utils/matAlgo14xDs.js]: Oops, `adt` is an undefined variable here. Amazing to me that it's not a lint error, but I guess the idea is that you're allowed to `typeof` any identifier, even one not in scope. Anyhow, it's a bug here; the type-narrowing code below can never fire, as you can verify by passing in a `number`-typed matrix and putting a console.log message in the block.

Comment (dvd101x) [reply src/type/matrix/utils/matAlgo14xDs.js]: Oh woow, nice catch! Thanks!

File: src/function/bitwise/leftShift.js [hunk 2]
```diff
@@ -27,8 +28,8 @@ export const createLeftShift = /* #__PURE__ */ factory(name, dependencies, ({ ty
   const matAlgo10xSids = createMatAlgo10xSids({ typed, DenseMatrix })
   const matAlgo11xS0s = createMatAlgo11xS0s({ typed, equalScalar })
   const matAlgo14xDs = createMatAlgo14xDs({ typed })
+  const matAlgo15xAs = createMatAlgo15xAs()
   const matrixAlgorithmSuite = createMatrixAlgorithmSuite({ typed, matrix, concat })
```
Comment (gwhitney) [inline src/function/bitwise/leftShift.js]: This `concat` is not actually a dependency of matrixAlgorithmSuite. Since you are here, please remove it. Most likely that will allow `concat` to be removed as a dependency altogether.

File: docs/datatypes/matrices.md [hunk 3]
```diff
@@ -12,7 +12,10 @@ dense and sparse matrices.
 Math.js supports two types of matrices:
 
 - `Array`, a regular JavaScript array. A multidimensional array can be created
-  by nesting arrays.
+  by nesting arrays. If the elements of an array are of the same size, it is a
+  rectangular array. If the elements are all arrays but not of the same size,
```
Comment (gwhitney) [inline docs/datatypes/matrices.md]: You should say that these words "rectangular", "jagged", "heterogeneous" are the terminology mathjs will use -- it's not like these are universally standard terms.

File: docs/datatypes/matrices.md [hunk 4]
```diff
@@ -224,6 +227,27 @@ If you have a matrix where the first dimension means `x` and the second
 means `y`, this will look confusing since `x` is printed as _column_ 
 (vertically) and `y` as _row_ (horizontally).
 
+## Not rectangular arrays
+
```
Comment (gwhitney) [inline docs/datatypes/matrices.md:231]: Should that be "Non-rectangular arrays" ?

File: docs/datatypes/matrices.md [hunk 5]
```diff
@@ -224,6 +227,27 @@ If you have a matrix where the first dimension means `x` and the second
...
+By nesting arrays it is possible to have arrays that are not rectangular, for example.
+```js
+[[1, 2], [3, 4]] // rectangular of size [2, 2]
+[[1, 2], [3]]    // jagged
+[[1, 2], 3]      // heterogeneous
+```
+
+These types of arrays can't be converted to a matrix, but many operations are available for them.
```
Comment (gwhitney) [inline docs/datatypes/matrices.md]: Say "Jagged and heterogeneous arrays" instead of "These types of arrays" because one of the examples you just showed was rectangular and _can_ be converted to a matrix.

File: docs/datatypes/matrices.md [hunk 6]
```diff
@@ -224,6 +227,27 @@ If you have a matrix where the first dimension means `x` and the second
...
+const A = [[1, 2], 3]
+math.add(A, 1)
+math.map(A, a => a+1)
+math.forEach(A, a => console.log(a))
+```
+Many matrix functions expect a rectangular array and might provide unexpected results with non rectangular arrays, for example.
+```js
+math.size([[1, 2], [3]]) // [2, 2]
+```
+The process of validation for rectangularity is expensive and this provides a fast way of working with nested arrays of many kinds.
```
Comment (gwhitney) [inline docs/datatypes/matrices.md]: The antecedent of "this" in "this provides" is unclear. Please clarify exactly what provides a fast way of working with nested arrays.

File: src/function/bitwise/rightArithShift.js [hunk 7]
```diff
@@ -27,8 +28,8 @@ export const createRightArithShift = /* #__PURE__ */ factory(name, dependencies,
   const matAlgo10xSids = createMatAlgo10xSids({ typed, DenseMatrix })
   const matAlgo11xS0s = createMatAlgo11xS0s({ typed, equalScalar })
   const matAlgo14xDs = createMatAlgo14xDs({ typed })
+  const matAlgo15xAs = createMatAlgo15xAs()
   const matrixAlgorithmSuite = createMatrixAlgorithmSuite({ typed, matrix, concat })
```
Comment (gwhitney) [inline src/function/bitwise/rightArithShift.js]: Same `concat` removal here.

File: src/function/bitwise/rightLogShift.js [hunk 8]
```diff
@@ -26,8 +27,8 @@ export const createRightLogShift = /* #__PURE__ */ factory(name, dependencies, (
   const matAlgo10xSids = createMatAlgo10xSids({ typed, DenseMatrix })
   const matAlgo11xS0s = createMatAlgo11xS0s({ typed, equalScalar })
   const matAlgo14xDs = createMatAlgo14xDs({ typed })
+  const matAlgo15xAs = createMatAlgo15xAs()
   const matrixAlgorithmSuite = createMatrixAlgorithmSuite({ typed, matrix, concat })
```
Comment (gwhitney) [inline src/function/bitwise/rightLogShift.js]: And remove `concat` here too.

File: src/type/matrix/utils/matAlgo14xDs.js [hunk 9]
```diff
@@ -22,54 +21,19 @@ export const createMatAlgo14xDs = /* #__PURE__ */ factory(name, dependencies, ({
...
     if (typeof adt === 'string') {
-      // datatype
-      dt = adt
       // convert b to the same datatype
-      b = typed.convert(b, dt)
+      b = typed.convert(b, adt)
       // callback
-      cf = typed.find(callback, [dt, dt])
+      cf = typed.find(callback, [adt, adt])
     }
```
Comment (gwhitney) [inline src/type/matrix/utils/matAlgo14xDs.js:35]: I realize that you didn't create this algorithm for dealing with the case when the matrix is of a known datatype, but it doesn't seem correct. For example, consider the case of a number matrix and adding a bignumber. Normally a number plus a bignumber is a bignumber. Since addition distributes over the entries of a matrix, I would expect a matrix of numbers, plus a bignumber, to produce a matrix of bignumbers. But by the above logic, instead the bignumber will be converted to a number (possibly losing precision, and since this is an explicit call to convert, there will be no warning), and you will end up with a matrix of numbers. That seems buggy, especially the potential  un-warned loss of precision. If you agree, I would personally be fine folding in a fix to this concern (as long as it is not breaking) into this PR. However @josdejong may disagree, and want addressing this potential issue to be in a separate PR. If so, or if it is breaking, please file an issue for the type-handling of matrix-scalar operations, noting whether it is breaking. Thanks!

File: src/type/matrix/utils/matAlgo15xAs.js [hunk 10]
```diff
@@ -0,0 +1,26 @@
+import { factory } from '../../../utils/factory.js'
+import { deepMap as map } from '../../../utils/array.js'
+
+const name = 'matAlgo15xAs'
+const dependencies = []
+
+export const createMatAlgo15xAs = /* #__PURE__ */ factory(name, dependencies, () => {
+  /**
+   * Iterates over Array items and invokes the callback function f(Aij..z, b).
+   * Callback function invoked MxN times.
```
Comment (gwhitney) [inline src/type/matrix/utils/matAlgo15xAs.js]: Since in this case the Array may quite explicitly not be rectangular, saying "MxN" is a bit misleading. Consider changing to something like "Callback function invoked once for each entry of A."

File: src/type/matrix/utils/matAlgo15xAs.js [hunk 11]
```diff
@@ -0,0 +1,26 @@
...
+   * @param {Scalar}   b                 The Scalar value
+   * @param {Function} cf                The f(Aij..z,b) operation to invoke
+   * @param {boolean}  inverse           A true value indicates callback should be invoked f(b,Aij..z)
+   *
+   * @return {Array}                    Array (C)
+   *
+   * https://github.com/josdejong/mathjs/pull/346#issuecomment-97659042
+   */
+  return function matAlgo15xAs (a, b, cf, inverse) {
+    return inverse ? map(a, v => cf(b, v)) : map(a, v => cf(v, b))
```
Comment (gwhitney) [inline src/type/matrix/utils/matAlgo15xAs.js]: For sufficiently large arrays, is it worth checking the array for type-homogeneity of its leaf entries, and if they are type-homogeneous, doing the appropriate typed.find on cf before calling map?  I guess the same question goes for Algorithm 14: if the matrix does not know if it has a uniform type, is there a size at which it becomes advantageous to first check if the matrix is uniform in type, and specializing the callback function if it is?

**Review by gwhitney — CHANGES_REQUESTED** [review]
Excellent, this is shaping up. A few more things to consider.

File: src/type/matrix/utils/matAlgo14xDs.js (hunk 9 above)
Comment (dvd101x) [reply src/type/matrix/utils/matAlgo14xDs.js:35]: For this I tried to maintain behavior as is. Maybe this could be addressed in a different PR.

Currently add a Matrix of numbers to a big number throws an error but tries to convert the bigNumber to number.

```js
math.add(math.matrix([1], "dense", "number"), math.bignumber(1))   // Uncaught Error: Cannot convert 1 to number
```
I agree it's not right and the same goes for `map` where it assumes that if the input is of a certain type the output will be as well.

```js
math.matrix([1], "dense", "number").map(x => math.add(x, math.bignumber(1)))  // returns a matrix of datatype "number" that contains bignumbers.
```
I don't see an easy fix about the types for when a `map` accepts a callback, other than checking the output.

But for operators maybe there is a way specific to each operator and datatype or a database of two type inputs equals a type output.

Comment (dvd101x) [reply src/type/matrix/utils/matAlgo14xDs.js:35]: I might be wrong, I will validate again if I'm changing the behavior.

Comment (gwhitney) [reply src/type/matrix/utils/matAlgo14xDs.js:35]: OK, well in the meantime I have filed #3612; you can address it or not in this PR as you and Jos see fit, but we should definitely fix it at some point in the not-too-distant future since it is definitely a bug.

**Comment by dvd101x** [comment]
After including benchmarks, there is a big benefit of not converting arrays to matrices and small benefit of using the DenseMatrix.map method.

image

File: src/type/matrix/utils/matAlgo14xDs.js (hunk 9 above)
Comment (josdejong) [reply src/type/matrix/utils/matAlgo14xDs.js:35]: Thanks for bringing this issue up Glen, we should indeed fix this behavior. But best to do that in a separate PR I think.

File: src/type/matrix/utils/matAlgo15xAs.js (hunk 10 above)
Comment (dvd101x) [reply src/type/matrix/utils/matAlgo15xAs.js]: Thanks! just addressed this issue. Please review

File: src/function/bitwise/rightLogShift.js (hunk 8 above)
Comment (dvd101x) [reply src/function/bitwise/rightLogShift.js]: Thanks! just addressed this issue. Please review

File: src/function/bitwise/rightArithShift.js (hunk 7 above)
Comment (dvd101x) [reply src/function/bitwise/rightArithShift.js]: Thanks! just addressed this issue.

File: docs/datatypes/matrices.md (hunk 6 above)
Comment (dvd101x) [reply docs/datatypes/matrices.md]: Thanks! just addressed this issue.

File: docs/datatypes/matrices.md (hunk 5 above)
Comment (dvd101x) [reply docs/datatypes/matrices.md]: Thanks for the thorough read. Just addressed this issue.

File: docs/datatypes/matrices.md (hunk 4 above)
Comment (dvd101x) [reply docs/datatypes/matrices.md:231]: Thanks! just addressed this.

File: docs/datatypes/matrices.md (hunk 3 above)
Comment (dvd101x) [reply docs/datatypes/matrices.md]: Thanks, included a brief explanation of the terminology that would be used. I'm not familiar weather or not these are known, but took references of wikipedia to define the names.

File: src/function/bitwise/leftShift.js (hunk 2 above)
Comment (dvd101x) [reply src/function/bitwise/leftShift.js]: Thanks! just addressed this.

File: src/type/matrix/utils/matAlgo15xAs.js (hunk 11 above)
Comment (dvd101x) [reply src/type/matrix/utils/matAlgo15xAs.js]: Thanks Glen

It's a fair point, I certainly would like to find that size. I think this idea might apply to many other cases like a matrix of unknown type or doing `map` and `forEach` on nested arrays. Also there is a cost of finding the size for nested arrays if they are jagged or heterogeneous, practically counting all of them.

At some point I tested memoizing the function found from the typed function in optimizeCallback but didn't pan out as the `try catch` needed to try the memoized signature function and then if it didn't work find a new one on the typed function was more expensive.

There is a cost of applying a typed function and they have many caveats, some of them are addressed by `optimizeCallback` but I don't know if other than finding the type of an argument there might be other costs.

Do you think this could be addressed as a separate topic?

File: src/type/matrix/utils/matAlgo14xDs.js (hunk 9 above)
Comment (dvd101x) [reply src/type/matrix/utils/matAlgo14xDs.js:35]: Hi, I did validate and I think the original behavior is maintained, please let me know if I'm mistaken.

**Comment by dvd101x** [comment]
Hi, all comments are addressed either in code or as a reply. This is ready for review again.

File: src/type/matrix/utils/matAlgo15xAs.js (hunk 11 above)
Comment (gwhitney) [reply src/type/matrix/utils/matAlgo15xAs.js]: OK, fair enough, please just file a discussion (or issue if you think warranted) and link it here and I will resolve this conversation.

Comment (dvd101x) [reply src/type/matrix/utils/matAlgo15xAs.js]: I made this reply according to Jos's comment.

https://github.com/josdejong/mathjs/discussions/3610#discussioncomment-15330368

Do you think it's ok or shall I make a separate discussion?

Comment (gwhitney) [reply src/type/matrix/utils/matAlgo15xAs.js]: No that's fine, resolving.

File: src/type/matrix/utils/matAlgo15xAs.js [hunk 12]
```diff
@@ -0,0 +1,26 @@
+import { factory } from '../../../utils/factory.js'
+import { deepMap as map } from '../../../utils/array.js'
+
+const name = 'matAlgo15xAs'
+const dependencies = []
+
+export const createMatAlgo15xAs = /* #__PURE__ */ factory(name, dependencies, () => {
+  /**
+   * Iterates over Array items and invokes the callback function f(Aij..z, b).
+   * Callback function invoked once for each item.
```
Comment (gwhitney) [inline src/type/matrix/utils/matAlgo15xAs.js]: Should this say "Deeply iterates over the given Array" or something like that to make it clear that it is not just calling f(a, b) for each (direct) entry a of A? Just a thought, either change or let me know you think it's OK as is.

**Comment by gwhitney** [comment]
Now we come to the difficulty that at this point, PRs are supposed to have per-function HISTORY for the functions they touch. I had hoped to get one of my PRs that touches a lot of functions to the point of going in to alleviate this big task before anyone else, but with the rate that Jos can review things and by other coincidences it seems as though you are getting there first. How would you like to handle this? Might we split up the chore of inserting such histories for the functions touched in this PR? Let me know your thoughts.

**Comment by dvd101x** [comment]
Most of the functions touched in this PR were due to the removal of `concat`.

I've been reviewing the history and this is mostly my fault as I did include them at #2895 because it was needed but then it should have been removed at #3220.

Please help me with an example of the history and I can gladly replicate it in the functions where `concat` was removed as a dependancy. 

We could split the rest.

**Comment by gwhitney** [comment]
> Please help me with an example of the history and I can gladly replicate it in the functions where `concat` was removed as a dependency.

A good current example is src/expressions/parse.js. Note that I do try to make the histories be from inception. The command `git log --follow -- filename` is super helpful for that as it tracks the files across renames as well -- some of the function implementations previously lived in different subdirectories, for example.

> We could split the rest.

Yes, that would be absolutely fine. Please just let me know which functions are "assigned" to me and when is a good time for me to work on them that I can push a commit to this PR without interfering with your work. Thanks!

**Comment by gwhitney** [comment]
Wow, thanks for all of the updated history files. Let me know if there are others on my list to supply History for. I also see failed tests, but didn't look at the details. Are these something you'll be taking care of? Thanks again.

**Comment by dvd101x** [comment]
I think the history files are done. Just please validate the changes made.

The error was due to formatting, so it should be ok now.

Just a clarification, some of the reference history files are sorted from newest to oldest and some are from oldest to newest. I also didn't apply them consistently. So please let me know which way to go. As a reference in [python documentation](https://docs.python.org/3/library/math.html#math.nan) they are from oldest to newest.

~~I still have one comment to address.~~

File: src/type/matrix/utils/matAlgo15xAs.js (hunk 12 above)
Comment (dvd101x) [reply src/type/matrix/utils/matAlgo15xAs.js]: I think you are right, in a DenseMatrix it's implied that the iteration is deep, but in Array it should be explicit.

Comment (gwhitney) [reply src/type/matrix/utils/matAlgo15xAs.js]: Looks good now, thanks, resolving.

**Comment by gwhitney** [comment]
> So please let me know which way to go. As a reference in [python documentation](https://docs.python.org/3/library/math.html#math.nan) they are from oldest to newest.

Since these are now the bulk of the HISTORY entries in the whole system, and most of them were newest to oldest, I just changed them all (and changed the archetype src/expressions/parse.js also to have this order). There are probably still some lurking oldest to newest, but we can fix those when the files are touched. Doing final review, then will merge.

**Comment by gwhitney** [comment]
Oh, actually in the final review, I checked out the reference to #3537, and noticed [this comment](https://github.com/josdejong/mathjs/discussions/3537#discussioncomment-14786748). So I added a test that I think corresponds to the expected/desired behavior for those cases. But it fails, and doesn't just produce a different value, it throws an error, and it's not even an error about not supporting that sort of ragged array. So I think it's a bug that should be addressed in this PR. @dvd101x do you want to take a look, or should I? And in either case, should mathjs support `map([[], [2]], square)` and produce `map([[], [4])` or should this be an error or have some other value? Thanks!

**Comment by dvd101x** [comment]
Thanks @gwhitney, I'll take a look and fix the failing test. It seems to be an issue in optimize callback with typed functions because `math.map([[], [2]], x => x**2)` works as expected.

**Comment by dvd101x** [comment]
Hi, just to confirm that this behavior was introduced by #3256 as stated at #3567.

I will look into a possible fix and look for the expected behavior in other languages.

**Comment by gwhitney** [comment]
Right, #3567 noted this behavior but did not address it, because at the time jagged arrays were not "officially allowed" by mathjs. Since this PR for the first time explicitly supports such operations, it is a good opportunity to settle what this behavior should be and implement it. Note that the decision _could_ be to throw an error in this case, but if so, it should be a "better" error than "Too many arguments in square," which seems to come out of nowhere. Thanks!

**Comment by dvd101x** [comment]
Hi. It must be ok now. Made a new function to find the first value and added some tests for optimizeCallback.
