### PR TITLE
Fix/2919 type exports manual

### LINKED ISSUE #2919: TS1203: Export assignment cannot be used when targeting  ECMAScript modules. Consider using 'export default' or another module format instead.
**Describe the bug**
Getting the following error:
```
tsc --noEmit        
../bla/node_modules/mathjs/types/index.d.ts:5:1 - error TS1203: Export assignment cannot be used when targeting 
ECMAScript modules. Consider using 'export default' or another module format instead.

5 export = math
  ~~~~~~~~~~~~~


Found 1 error in ../balances/node_modules/mathjs/types/index.d.ts:5
```

**To Reproduce**
I have `"type": "module"` in my `package.json` and 
```
"target": "ESNext",
"module": "ESNext",
"moduleResolution": "Node16"
```
in my TSConfig, using TS v5.0.2, it used to work with TS v4.9.5

### PR DESCRIPTION
**Pull request by josdejong**
Fix #2919 using the approach of Maxim worked out in #2932.

Changes:
- Renamed `MathJsStatic` into `MathJsInstance`
- The dependencies are no longer exported in `MathJsInstance` (they are not exported there in reality)
- Export all functions and constants of `MathJsInstance` as static constants.
- Document how to properly define types in `types/EXPLANATION.md`

To do:

- [x] Bring the types up to date with all changes done in the `v12` branch
- [x] Test thoroughly

### CODE REVIEW

**Comment by josdejong** [comment]
Published now in `v12.0.0`
