### ISSUE TITLE
TS1203: Export assignment cannot be used when targeting  ECMAScript modules. Consider using 'export default' or another module format instead.

### ISSUE THREAD

**Issue by Maxim-Mazurok** [josdejong/mathjs#2919]
**Describe the bug**
Getting the following error:
```
tsc --noEmit        
../bla/node_modules/mathjs/types/index.d.ts:5:1 - error TS1203: Export assignment cannot be used when targeting 
ECMAScript modules. Consider using 'export default' or another module format instead.

5 export = math
  ~~~~~~~~~~~~~


Found 1 error in ../balances/node_modules/mathjs/types/index.d.ts:5
```

**To Reproduce**
I have `"type": "module"` in my `package.json` and 
```
"target": "ESNext",
"module": "ESNext",
"moduleResolution": "Node16"
```
in my TSConfig, using TS v5.0.2, it used to work with TS v4.9.5

**Comment by Maxim-Mazurok** [comment]
Not entirely sure why, but using `"moduleResolution": "bundler"` instead of `Node16` resolved the issue

**Comment by josdejong** [comment]
Thanks for bringing this up. So in `index.d.ts` I see:

https://github.com/josdejong/mathjs/blob/7950d9c1f319242a41f8716eb6cbe352f2ce6384/types/index.d.ts#L3-L5


For reference: https://stackoverflow.com/questions/48708410/typescript-error-an-export-assignment-cannot-be-used-in-a-module-with-other-exp

Anyone able to see if we can/should improve on this?

**Comment by Maxim-Mazurok** [comment]
Not sure, I've tried the approach from the [answer](https://stackoverflow.com/a/51238234/4536543):
```d.ts
import { Decimal } from 'decimal.js'

type NoLiteralType<T> = T extends number
  ? number
  : T extends string
  ? string
  : T extends boolean
  ? boolean
  : T

declare module "math" {
  namespace math {
    //...
  }
  export = math;
}
```

And it resulted in the same error as in OP: `../../../../node_modules/mathjs/types/index.d.ts(6424,3): error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.`

**Comment by Maxim-Mazurok** [comment]
Also npm packages like `csv-parser` and `moment` seem to be using the same syntax as `mathjs` but no errors when trying to use and compile with old config... Maybe because they're both exporting a function instead of an object, not sure...

**Comment by josdejong** [comment]
Thanks for giving it a try Maxim. From what I understand from it, we should get rid of the `export = math` since that results in a CommonJS module, and instead use `export default math` to get a modern ES module. I briefly tried that but get a lot of errors then when running the tests of the TypeScript definitions.

**Comment by Maxim-Mazurok** [comment]
Hey @josdejong
I did get errors you mentioned and came up with two potential solutions:
1. https://github.com/josdejong/mathjs/pull/2931
2. https://github.com/josdejong/mathjs/pull/2932

Option 1 potentially breaks integrations and changes public API. Option 2 is safer, but ideally requires automation. I couldn't find a way to replicate previous behavior, my guess is that such broad ambiguous exports are not in ESM philosophy so likely aren't supported. I just ran a few regexes to extract exports, two of them trigger eslint errors, and there's also `import()` method that can't be exported at all as far as I can tell.

**Comment by Maxim-Mazurok** [comment]
This also might help: https://arethetypeswrong.github.io/?p=mathjs%4011.8.0

**Comment by josdejong** [comment]
Hmm. So both potential solutions are not ideal yet. Thanks for working them out!

Do you have any understanding on why `export default math` would not work? 

Would it work to remove the namespace and only export the interface `MathJsStatic`? (and maybe rename it to `MathJs`)

**Comment by Maxim-Mazurok** [comment]
I'm sorry, I've completed the transition to CJS from ESM because NX doesn't have proper support for ESM yet, so this issue is no longer relevant to me, and a good solution isn't apparent to me, so I hope someone else can pick it up from here, unsubscribing for now, cheers!

**Comment by josdejong** [comment]
Good to hear you have a solution for your case. Thanks for your work on solving this! 

I'll close your two PR's for the time being until someone can pick this up.

**Comment by nalply** [comment]
I will try to pick this up. Let's hope that I find a solution.

**Comment by josdejong** [comment]
Thanks for your offer @nalply ! Maxim did explore a couple of approaches already, that may serve as a good start.

**Comment by nalply** [comment]
Option 2 compiles fine for me, however the generated file in lib/esm/type/complex/Complex.js has SyntaxError: ambiguous indirect export: default, because of this line:

https://github.com/josdejong/mathjs/blob/develop/src/type/complex/Complex.js#L1

I will need to clone mathjs and tinker a bit.

Please tell me if I am barking up the wrong tree.

**Comment by nalply** [comment]
The problem lies with complex.js which uses old fashioned JS to define the class `Complex`. Firefox didn't like something in this code but I didn't find out what exactly. Something seems to be ambiguous. One try was to rename the node package, another one to change the way the constructor function is assigned to `module.exports`, but it didn't work out and the butchering of code left a bad taste in my mouth.

Meanwhile I decided to stop yak shaving and continuing with my project without fractions and complex numbers to get a MVP. Perhaps a later version of mathjs will solve this problem. If not, perhaps a rewrite of complex.js to modern JS would make sense.

I am sorry.

**Comment by josdejong** [comment]
> I want to program in TypeScript for the browser without bundling. 

🤔 hm are you trying to load non-bundled code in the browser? I'm not sure but I guess there are two different issues in play then: one is the `export = math` issue. And the other is that some of the dependencies are not ES modules, making it currently impossible to load the non-bundled code in a browser, see #1841, #1928. In this issue (#2919) we try to tackle the `export = math` issue

**Comment by nalply** [comment]
> [...] I guess there are two different issues in play then: one is the export = math issue. And the other is that some of the dependencies are not ES modules [...]

Yeah!

I forked complex.js and fraction.js yesterday and all is well, development has been ensuing since then rather smoothly. I am using https://modern-web.dev/docs/dev-server/overview/ which compiles TypeScript on the fly, and I hacked a small plugin to do some more on-the-fly processing and this makes me happy. YOLO.

**Comment by josdejong** [comment]
😂 👍

**Comment by hfhchan-plb** [comment]
This is partly because TypeScript expects you to ship two different .d.ts files, one for cjs, and one for esm.

See: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

```
It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them. Every declaration file is interpreted either as a CommonJS module or as an ES module, based on its file extension and the "type" field of the package.json, and this detected module kind must match the module kind that Node will detect for the corresponding JavaScript file for type checking to be correct. Attempting to use a single .d.ts file to type both an ES module entrypoint and a CommonJS entrypoint will cause TypeScript to think only one of those entrypoints exists, causing compiler errors for users of the package.
```

As of now, the package.json looks like this:
```
    ".": {
      "types": "./types/index.d.ts",
      "import": "./lib/esm/index.js",
      "require": "./lib/cjs/index.js"
    },
```

It should look like this:
```
    ".": {
      "import": "./lib/esm/index.js",
      "require": "./lib/cjs/index.js"
    },
```
with the `index.d.ts` copied into `./lib/esm/` and `./lib/cjs`

```
    ".": {
      "import": {
        "types": "./types/index.d.ts",
        "default": "./lib/esm/index.js"
      }
      "require": {
        "types": "./types/index.d.cts",
        "default": "./lib/cjs/index.js"
      }
    },
```
with `index.d.ts` duplicated to `index.d.cts`.

No other changes are necessary.

**Comment by josdejong** [comment]
O wow, that easy? That would be great!

@hfhchan-plb so can the `index.d.cts` contain `import { Decimal } from 'decimal.js'` and `export ...` then? I.e. shouldn't it be refactored to actual CJS use `require` and `module.exports`?

I've prepared a PR in #3021, anyone able to have a look or even better: verify whether this PR solves the issue?

**Comment by hfhchan-plb** [comment]
> so can the index.d.cts contain import { Decimal } from 'decimal.js' and export ... then?

Yes. The `import` / `export` syntax in .d.cts files is the TypeScript import syntax, not the CJS one.

> I.e. shouldn't it be refactored to actual CJS use require and module.exports?

No. If you do that, then TS stops recognizing it as a types file. :shrug:

**Comment by hfhchan-plb** [comment]
> I've prepared a PR in https://github.com/josdejong/mathjs/pull/3021, anyone able to have a look or even better: verify whether this PR solves the issue?

LGTM

**Comment by josdejong** [comment]
Thanks for checking it out! Will merge it soon.

**Comment by josdejong** [comment]
I've done some testing with #3021, having alternative entry points in the package.json file. This does not solve the issue unfortunately. 

So I think we should resort to one of the options worked out by Maxim, see https://github.com/josdejong/mathjs/issues/2919#issuecomment-1501064677). I think the second option is best since it does not need any special tricks: it is just the dumb way to define that function `create` returns a mathjs instance, and that the library exposes a static instance too. We have to define it twice. That is unfortunate and I agree with Maxim that we should automate that. In the long term I want to autogenerate all type definitions, but for the time being we will have to maintain it manually. 

I've now created an new PR #3078 using the approach of option 2 of Maxim, and added documentation. Still need to do testing and some last thingies. Feedback would be welcome.

**Comment by josdejong** [comment]
Fixed now in `v12.0.0` via #3079
